// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_share_links.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeviceShareLink = `-- name: CreateDeviceShareLink :one
INSERT INTO device_share_links (device_id, created_by, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, device_id, created_by, token_hash, created_at, expires_at, revoked_at
`

type CreateDeviceShareLinkParams struct {
	DeviceID  pgtype.UUID
	CreatedBy pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateDeviceShareLink(ctx context.Context, arg CreateDeviceShareLinkParams) (DeviceShareLink, error) {
	row := q.db.QueryRow(ctx, createDeviceShareLink,
		arg.DeviceID,
		arg.CreatedBy,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i DeviceShareLink
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CreatedBy,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getValidDeviceShareLinkByHash = `-- name: GetValidDeviceShareLinkByHash :one
SELECT dsl.id, dsl.device_id, dsl.created_by, dsl.token_hash,
       dsl.created_at, dsl.expires_at, dsl.revoked_at, d.name AS device_name
FROM device_share_links AS dsl
JOIN devices AS d ON d.id = dsl.device_id AND d.deleted_at IS NULL
WHERE dsl.token_hash = $1
  AND dsl.revoked_at IS NULL
  AND dsl.expires_at > NOW()
`

type GetValidDeviceShareLinkByHashRow struct {
	ID         pgtype.UUID
	DeviceID   pgtype.UUID
	CreatedBy  pgtype.UUID
	TokenHash  string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	DeviceName string
}

func (q *Queries) GetValidDeviceShareLinkByHash(ctx context.Context, tokenHash string) (GetValidDeviceShareLinkByHashRow, error) {
	row := q.db.QueryRow(ctx, getValidDeviceShareLinkByHash, tokenHash)
	var i GetValidDeviceShareLinkByHashRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.CreatedBy,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.DeviceName,
	)
	return i, err
}

const listActiveDeviceShareLinks = `-- name: ListActiveDeviceShareLinks :many
SELECT id, device_id, created_by, token_hash, created_at, expires_at, revoked_at
FROM device_share_links
WHERE device_id = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListActiveDeviceShareLinks(ctx context.Context, deviceID pgtype.UUID) ([]DeviceShareLink, error) {
	rows, err := q.db.Query(ctx, listActiveDeviceShareLinks, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceShareLink
	for rows.Next() {
		var i DeviceShareLink
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.CreatedBy,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDeviceShareLink = `-- name: RevokeDeviceShareLink :exec
UPDATE device_share_links
SET revoked_at = NOW()
WHERE id = $1
  AND device_id = $2
  AND revoked_at IS NULL
`

type RevokeDeviceShareLinkParams struct {
	ID       pgtype.UUID
	DeviceID pgtype.UUID
}

func (q *Queries) RevokeDeviceShareLink(ctx context.Context, arg RevokeDeviceShareLinkParams) error {
	_, err := q.db.Exec(ctx, revokeDeviceShareLink, arg.ID, arg.DeviceID)
	return err
}
