// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDevicesForUser = `-- name: CountDevicesForUser :one
SELECT COUNT(*)::bigint AS count
FROM devices d
INNER JOIN user_device_access uda
  ON d.id = uda.device_id AND uda.deleted_at IS NULL
WHERE uda.user_id = $1
  AND d.deleted_at IS NULL
`

// Returns the total count of devices a user has access to.
// Used for pagination metadata.
func (q *Queries) CountDevicesForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDevicesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (uuid_firmware, name, vehicle_type)
VALUES (
  $1,
  $2,
  $3::device_vehicle_type
)
RETURNING id, uuid_firmware, name, vehicle_type, created_at, last_contact_at, deleted_at
`

type CreateDeviceParams struct {
	UuidFirmware string
	Name         string
	VehicleType  DeviceVehicleType
}

type CreateDeviceRow struct {
	ID            pgtype.UUID
	UuidFirmware  string
	Name          string
	VehicleType   DeviceVehicleType
	CreatedAt     pgtype.Timestamptz
	LastContactAt pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

// Creates a new device. uuid_firmware must be globally unique (DB-enforced).
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (CreateDeviceRow, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.UuidFirmware, arg.Name, arg.VehicleType)
	var i CreateDeviceRow
	err := row.Scan(
		&i.ID,
		&i.UuidFirmware,
		&i.Name,
		&i.VehicleType,
		&i.CreatedAt,
		&i.LastContactAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, uuid_firmware, name, vehicle_type, created_at, last_contact_at, deleted_at
FROM devices
WHERE id = $1 AND deleted_at IS NULL
`

type GetDeviceByIDRow struct {
	ID            pgtype.UUID
	UuidFirmware  string
	Name          string
	VehicleType   DeviceVehicleType
	CreatedAt     pgtype.Timestamptz
	LastContactAt pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

// Standard lookup by primary key. Filters out soft-deleted devices.
func (q *Queries) GetDeviceByID(ctx context.Context, id pgtype.UUID) (GetDeviceByIDRow, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i GetDeviceByIDRow
	err := row.Scan(
		&i.ID,
		&i.UuidFirmware,
		&i.Name,
		&i.VehicleType,
		&i.CreatedAt,
		&i.LastContactAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeviceByIDForUser = `-- name: GetDeviceByIDForUser :one
SELECT
  d.id,
  d.uuid_firmware,
  d.name,
  d.vehicle_type,
  d.created_at,
  d.last_contact_at,
  uda.role AS access_role
FROM devices d
INNER JOIN user_device_access uda
  ON d.id = uda.device_id AND uda.deleted_at IS NULL
WHERE d.id = $1
  AND uda.user_id = $2
  AND d.deleted_at IS NULL
`

type GetDeviceByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetDeviceByIDForUserRow struct {
	ID            pgtype.UUID
	UuidFirmware  string
	Name          string
	VehicleType   DeviceVehicleType
	CreatedAt     pgtype.Timestamptz
	LastContactAt pgtype.Timestamptz
	AccessRole    string
}

// Returns the device only if the given user has access (any role).
// Returns sql.ErrNoRows when the device does not exist OR the user has no
// access. The handler maps both to 404 to avoid leaking which IDs exist.
func (q *Queries) GetDeviceByIDForUser(ctx context.Context, arg GetDeviceByIDForUserParams) (GetDeviceByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getDeviceByIDForUser, arg.ID, arg.UserID)
	var i GetDeviceByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.UuidFirmware,
		&i.Name,
		&i.VehicleType,
		&i.CreatedAt,
		&i.LastContactAt,
		&i.AccessRole,
	)
	return i, err
}

const getDeviceByUUIDFirmware = `-- name: GetDeviceByUUIDFirmware :one
SELECT id, uuid_firmware, name, vehicle_type, created_at, last_contact_at, deleted_at
FROM devices
WHERE uuid_firmware = $1 AND deleted_at IS NULL
`

type GetDeviceByUUIDFirmwareRow struct {
	ID            pgtype.UUID
	UuidFirmware  string
	Name          string
	VehicleType   DeviceVehicleType
	CreatedAt     pgtype.Timestamptz
	LastContactAt pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

// Hot auth path for the IoT device authentication flow.
// The ESP32 sends its uuid_firmware, the backend resolves it to a device row.
func (q *Queries) GetDeviceByUUIDFirmware(ctx context.Context, uuidFirmware string) (GetDeviceByUUIDFirmwareRow, error) {
	row := q.db.QueryRow(ctx, getDeviceByUUIDFirmware, uuidFirmware)
	var i GetDeviceByUUIDFirmwareRow
	err := row.Scan(
		&i.ID,
		&i.UuidFirmware,
		&i.Name,
		&i.VehicleType,
		&i.CreatedAt,
		&i.LastContactAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeviceIDByUuidFirmware = `-- name: GetDeviceIDByUuidFirmware :one
SELECT id FROM devices WHERE uuid_firmware = $1 AND deleted_at IS NULL
`

// Lightweight lookup that only returns the device id. Used by the IoT
// location-ingest middleware after the API key has authenticated the
// caller: we know the key's device_id, but we still want to confirm
// the path's uuid_firmware maps to the same device row before we accept
// the payload. Returns sql.ErrNoRows when the device does not exist OR
// is soft-deleted; the middleware maps both to 404.
func (q *Queries) GetDeviceIDByUuidFirmware(ctx context.Context, uuidFirmware string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getDeviceIDByUuidFirmware, uuidFirmware)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listDevicesForUser = `-- name: ListDevicesForUser :many
SELECT
  d.id,
  d.uuid_firmware,
  d.name,
  d.vehicle_type,
  d.created_at,
  d.last_contact_at,
  uda.role AS access_role
FROM devices d
INNER JOIN user_device_access uda
  ON d.id = uda.device_id AND uda.deleted_at IS NULL
WHERE uda.user_id = $1
  AND d.deleted_at IS NULL
ORDER BY d.created_at DESC
`

type ListDevicesForUserRow struct {
	ID            pgtype.UUID
	UuidFirmware  string
	Name          string
	VehicleType   DeviceVehicleType
	CreatedAt     pgtype.Timestamptz
	LastContactAt pgtype.Timestamptz
	AccessRole    string
}

// Returns the devices the given user has access to, with the access role
// from user_device_access. Used by the dashboard "my devices" view.
// Filters out soft-deleted devices and soft-deleted access grants.
func (q *Queries) ListDevicesForUser(ctx context.Context, userID pgtype.UUID) ([]ListDevicesForUserRow, error) {
	rows, err := q.db.Query(ctx, listDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesForUserRow
	for rows.Next() {
		var i ListDevicesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UuidFirmware,
			&i.Name,
			&i.VehicleType,
			&i.CreatedAt,
			&i.LastContactAt,
			&i.AccessRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesForUserPaginated = `-- name: ListDevicesForUserPaginated :many
SELECT d.id, d.uuid_firmware, d.name, d.vehicle_type, d.created_at, d.last_contact_at
FROM devices d
INNER JOIN user_device_access uda
  ON d.id = uda.device_id AND uda.deleted_at IS NULL
WHERE uda.user_id = $1
  AND d.deleted_at IS NULL
ORDER BY d.created_at DESC
LIMIT $2 OFFSET $3
`

type ListDevicesForUserPaginatedParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

type ListDevicesForUserPaginatedRow struct {
	ID            pgtype.UUID
	UuidFirmware  string
	Name          string
	VehicleType   DeviceVehicleType
	CreatedAt     pgtype.Timestamptz
	LastContactAt pgtype.Timestamptz
}

// Returns paginated devices for a user with access.
// Used by the user profile endpoint to list user's devices.
func (q *Queries) ListDevicesForUserPaginated(ctx context.Context, arg ListDevicesForUserPaginatedParams) ([]ListDevicesForUserPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listDevicesForUserPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesForUserPaginatedRow
	for rows.Next() {
		var i ListDevicesForUserPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UuidFirmware,
			&i.Name,
			&i.VehicleType,
			&i.CreatedAt,
			&i.LastContactAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesForUserWithAccessPaginated = `-- name: ListDevicesForUserWithAccessPaginated :many
SELECT
  d.id,
  d.uuid_firmware,
  d.name,
  d.vehicle_type,
  d.created_at,
  d.last_contact_at,
  uda.role AS access_role
FROM devices d
INNER JOIN user_device_access uda
  ON d.id = uda.device_id AND uda.deleted_at IS NULL
WHERE uda.user_id = $1
  AND d.deleted_at IS NULL
ORDER BY d.created_at DESC
LIMIT $2 OFFSET $3
`

type ListDevicesForUserWithAccessPaginatedParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

type ListDevicesForUserWithAccessPaginatedRow struct {
	ID            pgtype.UUID
	UuidFirmware  string
	Name          string
	VehicleType   DeviceVehicleType
	CreatedAt     pgtype.Timestamptz
	LastContactAt pgtype.Timestamptz
	AccessRole    string
}

// Returns paginated devices the given user has access to, with the access role.
// Used by the device list endpoint with pagination.
func (q *Queries) ListDevicesForUserWithAccessPaginated(ctx context.Context, arg ListDevicesForUserWithAccessPaginatedParams) ([]ListDevicesForUserWithAccessPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listDevicesForUserWithAccessPaginated, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesForUserWithAccessPaginatedRow
	for rows.Next() {
		var i ListDevicesForUserWithAccessPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UuidFirmware,
			&i.Name,
			&i.VehicleType,
			&i.CreatedAt,
			&i.LastContactAt,
			&i.AccessRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDevice = `-- name: SoftDeleteDevice :exec
UPDATE devices
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// Marks the device as deleted. CASCADE-safe: locations and api_keys
// are not touched (RESTRICT FKs).
func (q *Queries) SoftDeleteDevice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteDevice, id)
	return err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE devices
SET last_contact_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// Called by the device auth middleware on every successful request
// from the IoT device. Cheap, no RETURNING.
func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateDeviceLastSeen, id)
	return err
}

const updateDeviceName = `-- name: UpdateDeviceName :one
UPDATE devices
SET name = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, uuid_firmware, name, vehicle_type, created_at, last_contact_at, deleted_at
`

type UpdateDeviceNameParams struct {
	ID   pgtype.UUID
	Name string
}

type UpdateDeviceNameRow struct {
	ID            pgtype.UUID
	UuidFirmware  string
	Name          string
	VehicleType   DeviceVehicleType
	CreatedAt     pgtype.Timestamptz
	LastContactAt pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

// Updates the display name. Returns the updated row, or sql.ErrNoRows
// if the device does not exist or is soft-deleted.
func (q *Queries) UpdateDeviceName(ctx context.Context, arg UpdateDeviceNameParams) (UpdateDeviceNameRow, error) {
	row := q.db.QueryRow(ctx, updateDeviceName, arg.ID, arg.Name)
	var i UpdateDeviceNameRow
	err := row.Scan(
		&i.ID,
		&i.UuidFirmware,
		&i.Name,
		&i.VehicleType,
		&i.CreatedAt,
		&i.LastContactAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDeviceVehicleType = `-- name: UpdateDeviceVehicleType :one
UPDATE devices
SET vehicle_type = $1::device_vehicle_type
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, uuid_firmware, name, vehicle_type, created_at, last_contact_at, deleted_at
`

type UpdateDeviceVehicleTypeParams struct {
	VehicleType DeviceVehicleType
	ID          pgtype.UUID
}

type UpdateDeviceVehicleTypeRow struct {
	ID            pgtype.UUID
	UuidFirmware  string
	Name          string
	VehicleType   DeviceVehicleType
	CreatedAt     pgtype.Timestamptz
	LastContactAt pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

// Updates the vehicle type. Returns the updated row, or sql.ErrNoRows
// if the device does not exist or is soft-deleted.
func (q *Queries) UpdateDeviceVehicleType(ctx context.Context, arg UpdateDeviceVehicleTypeParams) (UpdateDeviceVehicleTypeRow, error) {
	row := q.db.QueryRow(ctx, updateDeviceVehicleType, arg.VehicleType, arg.ID)
	var i UpdateDeviceVehicleTypeRow
	err := row.Scan(
		&i.ID,
		&i.UuidFirmware,
		&i.Name,
		&i.VehicleType,
		&i.CreatedAt,
		&i.LastContactAt,
		&i.DeletedAt,
	)
	return i, err
}
