// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DeviceVehicleType string

const (
	DeviceVehicleTypeBicycle    DeviceVehicleType = "bicycle"
	DeviceVehicleTypeMotorcycle DeviceVehicleType = "motorcycle"
	DeviceVehicleTypeCar        DeviceVehicleType = "car"
	DeviceVehicleTypeTruck      DeviceVehicleType = "truck"
	DeviceVehicleTypeVan        DeviceVehicleType = "van"
	DeviceVehicleTypeOther      DeviceVehicleType = "other"
)

func (e *DeviceVehicleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceVehicleType(s)
	case string:
		*e = DeviceVehicleType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceVehicleType: %T", src)
	}
	return nil
}

type NullDeviceVehicleType struct {
	DeviceVehicleType DeviceVehicleType
	Valid             bool // Valid is true if DeviceVehicleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceVehicleType) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceVehicleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceVehicleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceVehicleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceVehicleType), nil
}

type UserRole string

const (
	UserRoleUser       UserRole = "user"
	UserRoleSuperAdmin UserRole = "super_admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Device struct {
	ID           pgtype.UUID
	UuidFirmware string
	Name         string
	CreatedAt    pgtype.Timestamptz
	LastSeenAt   pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	VehicleType  DeviceVehicleType
}

type DeviceApiKey struct {
	ID         pgtype.UUID
	DeviceID   pgtype.UUID
	KeyHash    string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type Location struct {
	DeviceID       pgtype.UUID
	RecordedAt     pgtype.Timestamptz
	Latitude       float64
	Longitude      float64
	Altitude       *float64
	Speed          *float64
	Accuracy       *float64
	BatteryVoltage *float64
	SignalStrength *int32
}

type PasswordResetToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	IpAddress string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID                 pgtype.UUID
	Email              string
	Role               UserRole
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	Name               string
	Lastname           string
	MustChangePassword bool
	EmailVerified      bool
	Image              *string
}

type UserDeviceAccess struct {
	UserID    pgtype.UUID
	DeviceID  pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
