// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentPasswordResetTokensForIP = `-- name: CountRecentPasswordResetTokensForIP :one
SELECT COUNT(*)::bigint AS count
FROM password_reset_tokens
WHERE ip_address = $1
  AND created_at > NOW() - $2::interval
`

type CountRecentPasswordResetTokensForIPParams struct {
	IpAddress string
	Column2   pgtype.Interval
}

// Per-IP sibling of CountRecentPasswordResetTokensForUser. Counts every
// token issued from the same IP within the lookback window.
func (q *Queries) CountRecentPasswordResetTokensForIP(ctx context.Context, arg CountRecentPasswordResetTokensForIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentPasswordResetTokensForIP, arg.IpAddress, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentPasswordResetTokensForUser = `-- name: CountRecentPasswordResetTokensForUser :one
SELECT COUNT(*)::bigint AS count
FROM password_reset_tokens
WHERE user_id = $1
  AND created_at > NOW() - $2::interval
`

type CountRecentPasswordResetTokensForUserParams struct {
	UserID  pgtype.UUID
	Column2 pgtype.Interval
}

// Rate-limit probe for "too many requests for this user". Counts every
// token issued for the user in the last 15 minutes, regardless of
// whether it's still outstanding — the limit is on dispatch, not on
// success.
func (q *Queries) CountRecentPasswordResetTokensForUser(ctx context.Context, arg CountRecentPasswordResetTokensForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentPasswordResetTokensForUser, arg.UserID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, ip_address, expires_at, used_at, created_at
FROM password_reset_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > NOW()
`

// Lookup used by the consume endpoint. Filters out used tokens and
// expired ones — if any condition fails, the row simply isn't returned
// and the caller surfaces ErrInvalidResetToken. Keeping them in one
// SELECT means the consume path is one round-trip.
func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertPasswordResetToken = `-- name: InsertPasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_hash, ip_address, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, ip_address, expires_at, used_at, created_at
`

type InsertPasswordResetTokenParams struct {
	UserID    pgtype.UUID
	TokenHash string
	IpAddress string
	ExpiresAt pgtype.Timestamptz
}

// Stores a new password-reset token. The caller is responsible for
// hashing the raw token (sha256) before passing token_hash in.
// ON CONFLICT DO NOTHING would not work because token_hash has a UNIQUE
// index — a collision is a security failure, not a normal outcome. The
// caller picks 32 bytes from crypto/rand, so collisions are not a concern.
func (q *Queries) InsertPasswordResetToken(ctx context.Context, arg InsertPasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, insertPasswordResetToken,
		arg.UserID,
		arg.TokenHash,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateOutstandingPasswordResetTokens = `-- name: InvalidateOutstandingPasswordResetTokens :exec
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE user_id = $1
  AND used_at IS NULL
  AND expires_at > NOW()
`

// On a fresh request, mark every still-outstanding (not used, not
// expired) token for the user as used so only the latest link works.
// Single-window invariant: at most one active link per user.
func (q *Queries) InvalidateOutstandingPasswordResetTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidateOutstandingPasswordResetTokens, userID)
	return err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :execrows
UPDATE password_reset_tokens
SET used_at = NOW()
WHERE id = $1
  AND used_at IS NULL
`

// Stamps used_at on a successful consume. The (id, used_at IS NULL)
// guard makes the operation idempotent: a second concurrent consume of
// the same token affects 0 rows and the caller surfaces
// ErrInvalidResetToken. This is how we make the token genuinely
// single-use even under a race.
func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markPasswordResetTokenUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
