name: Backend CI/CD

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-backend-ci-cd

      - name: Run tests
        working-directory: backend
        run: |
          echo "::group::Testing backend"
          go test ./internal/app/* -v
          echo "::endgroup::"

  backend-build:
    needs: [backend-test]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-backend-ci-cd

      - name: Build project
        working-directory: backend
        run: |
          echo "::group::Build backend"
          go build ./cmd/api
          echo "::endgroup::"

  backend-docker:
    needs: [backend-build]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Build docker image
        working-directory: backend
        run: |
          echo "::group::Build docker image"
          docker build -t chamito/open-gps-api:dev .
          echo "::endgroup::"

      - name: Push docker image
        working-directory: backend
        run: |
          echo "::group::Push docker image"
          docker login -u chamito -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker push chamito/open-gps-api:dev
          echo "::endgroup::"