name: Backend CI/CD

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  backend-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-backend-ci-cd

      - name: Run tests
        working-directory: backend
        run: |
          echo "::group::Testing backend"
          go test ./internal/app/* -v
          echo "::endgroup::"

  backend-build:
    needs: [backend-test]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-backend-ci-cd

      - name: Build project
        working-directory: backend
        run: |
          echo "::group::Build backend"
          go build ./cmd/api
          echo "::endgroup::"

  backend-docker:
    needs: [backend-build]
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Log in to Docker Hub
        run: |
          echo "::group::Docker login"
          docker login -u chamito -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          echo "::endgroup::"

      - name: Build docker image
        working-directory: backend
        run: |
          echo "::group::Build docker image"
          docker build -t chamito/open-gps-api:dev .
          echo "::endgroup::"

      - name: Push API image
        run: |
          echo "::group::Push API image"
          docker push chamito/open-gps-api:dev
          echo "::endgroup::"

      - name: Build migrate image
        run: |
          echo "::group::Build migrate image"
          docker build --pull -t chamito/open-gps-migrate:dev migrate
          echo "::endgroup::"

      - name: Push migrate image
        run: |
          echo "::group::Push migrate image"
          docker push chamito/open-gps-migrate:dev
          echo "::endgroup::"
